debug: false

fig:
  enabled: false
  bin: /usr/bin/fig

  # containing fig.yml file
  folders:
    # unique-name: path


icons:
  enabled: true

  # for a list see http://getbootstrap.com/components/#glyphicons
  container_regex:
     '/mysql/': "hdd"
     '/magento/': "shopping-cart"
     '/test/': "flag"